[2025-04-28T19:37:19.829+0000] {processor.py:186} INFO - Started process (PID=180) to work on /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:37:19.830+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lstm_refactored_dag.py for tasks to queue
[2025-04-28T19:37:19.832+0000] {logging_mixin.py:190} INFO - [2025-04-28T19:37:19.832+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:37:19.838+0000] {logging_mixin.py:190} INFO - [2025-04-28T19:37:19.837+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/lstm_refactored_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/lstm_refactored_dag.py", line 11, in <module>
    from src.utils.db_utils import setup_database
ModuleNotFoundError: No module named 'src'
[2025-04-28T19:37:19.838+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:37:19.849+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lstm_refactored_dag.py took 0.024 seconds
[2025-04-28T19:37:50.221+0000] {processor.py:186} INFO - Started process (PID=185) to work on /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:37:50.221+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lstm_refactored_dag.py for tasks to queue
[2025-04-28T19:37:50.223+0000] {logging_mixin.py:190} INFO - [2025-04-28T19:37:50.222+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:37:50.225+0000] {logging_mixin.py:190} INFO - [2025-04-28T19:37:50.225+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/lstm_refactored_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/lstm_refactored_dag.py", line 11, in <module>
    from src.utils.db_utils import setup_database
ModuleNotFoundError: No module named 'src'
[2025-04-28T19:37:50.226+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:37:50.237+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lstm_refactored_dag.py took 0.020 seconds
[2025-04-28T19:38:20.563+0000] {processor.py:186} INFO - Started process (PID=198) to work on /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:38:20.563+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lstm_refactored_dag.py for tasks to queue
[2025-04-28T19:38:20.564+0000] {logging_mixin.py:190} INFO - [2025-04-28T19:38:20.564+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:38:20.567+0000] {logging_mixin.py:190} INFO - [2025-04-28T19:38:20.566+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/lstm_refactored_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/lstm_refactored_dag.py", line 11, in <module>
    from src.utils.db_utils import setup_database
ModuleNotFoundError: No module named 'src'
[2025-04-28T19:38:20.567+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:38:20.579+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lstm_refactored_dag.py took 0.020 seconds
[2025-04-28T19:38:50.955+0000] {processor.py:186} INFO - Started process (PID=203) to work on /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:38:50.956+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lstm_refactored_dag.py for tasks to queue
[2025-04-28T19:38:50.958+0000] {logging_mixin.py:190} INFO - [2025-04-28T19:38:50.957+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:38:50.961+0000] {logging_mixin.py:190} INFO - [2025-04-28T19:38:50.960+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/lstm_refactored_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/lstm_refactored_dag.py", line 11, in <module>
    from src.utils.db_utils import setup_database
ModuleNotFoundError: No module named 'src'
[2025-04-28T19:38:50.961+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:38:50.974+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lstm_refactored_dag.py took 0.024 seconds
[2025-04-28T19:39:21.317+0000] {processor.py:186} INFO - Started process (PID=216) to work on /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:39:21.318+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lstm_refactored_dag.py for tasks to queue
[2025-04-28T19:39:21.319+0000] {logging_mixin.py:190} INFO - [2025-04-28T19:39:21.319+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:39:21.323+0000] {logging_mixin.py:190} INFO - [2025-04-28T19:39:21.322+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/lstm_refactored_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/lstm_refactored_dag.py", line 11, in <module>
    from src.utils.db_utils import setup_database
ModuleNotFoundError: No module named 'src'
[2025-04-28T19:39:21.323+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:39:21.335+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lstm_refactored_dag.py took 0.021 seconds
[2025-04-28T19:39:51.695+0000] {processor.py:186} INFO - Started process (PID=221) to work on /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:39:51.696+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lstm_refactored_dag.py for tasks to queue
[2025-04-28T19:39:51.700+0000] {logging_mixin.py:190} INFO - [2025-04-28T19:39:51.700+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:39:51.704+0000] {logging_mixin.py:190} INFO - [2025-04-28T19:39:51.703+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/lstm_refactored_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/lstm_refactored_dag.py", line 11, in <module>
    from src.utils.db_utils import setup_database
ModuleNotFoundError: No module named 'src'
[2025-04-28T19:39:51.704+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:39:51.715+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lstm_refactored_dag.py took 0.024 seconds
[2025-04-28T19:40:22.071+0000] {processor.py:186} INFO - Started process (PID=234) to work on /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:40:22.072+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lstm_refactored_dag.py for tasks to queue
[2025-04-28T19:40:22.074+0000] {logging_mixin.py:190} INFO - [2025-04-28T19:40:22.074+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:40:22.077+0000] {logging_mixin.py:190} INFO - [2025-04-28T19:40:22.076+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/lstm_refactored_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/lstm_refactored_dag.py", line 11, in <module>
    from src.utils.db_utils import setup_database
ModuleNotFoundError: No module named 'src'
[2025-04-28T19:40:22.077+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:40:22.089+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lstm_refactored_dag.py took 0.024 seconds
[2025-04-28T19:40:52.450+0000] {processor.py:186} INFO - Started process (PID=239) to work on /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:40:52.451+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lstm_refactored_dag.py for tasks to queue
[2025-04-28T19:40:52.453+0000] {logging_mixin.py:190} INFO - [2025-04-28T19:40:52.452+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:40:52.456+0000] {logging_mixin.py:190} INFO - [2025-04-28T19:40:52.455+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/lstm_refactored_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/lstm_refactored_dag.py", line 11, in <module>
    from src.utils.db_utils import setup_database
ModuleNotFoundError: No module named 'src'
[2025-04-28T19:40:52.456+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:40:52.468+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lstm_refactored_dag.py took 0.021 seconds
[2025-04-28T19:41:22.829+0000] {processor.py:186} INFO - Started process (PID=252) to work on /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:41:22.830+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lstm_refactored_dag.py for tasks to queue
[2025-04-28T19:41:22.832+0000] {logging_mixin.py:190} INFO - [2025-04-28T19:41:22.832+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:41:22.839+0000] {logging_mixin.py:190} INFO - [2025-04-28T19:41:22.837+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/lstm_refactored_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/lstm_refactored_dag.py", line 11, in <module>
    from src.utils.db_utils import setup_database
ModuleNotFoundError: No module named 'src'
[2025-04-28T19:41:22.840+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:41:22.863+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lstm_refactored_dag.py took 0.039 seconds
[2025-04-28T19:41:53.222+0000] {processor.py:186} INFO - Started process (PID=257) to work on /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:41:53.223+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lstm_refactored_dag.py for tasks to queue
[2025-04-28T19:41:53.225+0000] {logging_mixin.py:190} INFO - [2025-04-28T19:41:53.225+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:41:53.230+0000] {logging_mixin.py:190} INFO - [2025-04-28T19:41:53.229+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/lstm_refactored_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/lstm_refactored_dag.py", line 11, in <module>
    from src.utils.db_utils import setup_database
ModuleNotFoundError: No module named 'src'
[2025-04-28T19:41:53.231+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:41:53.243+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lstm_refactored_dag.py took 0.024 seconds
[2025-04-28T19:42:23.577+0000] {processor.py:186} INFO - Started process (PID=270) to work on /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:42:23.577+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lstm_refactored_dag.py for tasks to queue
[2025-04-28T19:42:23.579+0000] {logging_mixin.py:190} INFO - [2025-04-28T19:42:23.579+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:42:23.582+0000] {logging_mixin.py:190} INFO - [2025-04-28T19:42:23.581+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/lstm_refactored_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/lstm_refactored_dag.py", line 11, in <module>
    from src.utils.db_utils import setup_database
ModuleNotFoundError: No module named 'src'
[2025-04-28T19:42:23.582+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:42:23.593+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lstm_refactored_dag.py took 0.020 seconds
[2025-04-28T19:42:53.967+0000] {processor.py:186} INFO - Started process (PID=275) to work on /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:42:53.968+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lstm_refactored_dag.py for tasks to queue
[2025-04-28T19:42:53.969+0000] {logging_mixin.py:190} INFO - [2025-04-28T19:42:53.969+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:42:53.972+0000] {logging_mixin.py:190} INFO - [2025-04-28T19:42:53.971+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/lstm_refactored_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/lstm_refactored_dag.py", line 11, in <module>
    from src.utils.db_utils import setup_database
ModuleNotFoundError: No module named 'src'
[2025-04-28T19:42:53.972+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:42:53.983+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lstm_refactored_dag.py took 0.020 seconds
[2025-04-28T19:43:24.363+0000] {processor.py:186} INFO - Started process (PID=288) to work on /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:43:24.363+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lstm_refactored_dag.py for tasks to queue
[2025-04-28T19:43:24.366+0000] {logging_mixin.py:190} INFO - [2025-04-28T19:43:24.366+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:43:24.373+0000] {logging_mixin.py:190} INFO - [2025-04-28T19:43:24.371+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/lstm_refactored_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/lstm_refactored_dag.py", line 11, in <module>
    from src.utils.db_utils import setup_database
ModuleNotFoundError: No module named 'src'
[2025-04-28T19:43:24.374+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:43:24.392+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lstm_refactored_dag.py took 0.033 seconds
[2025-04-28T19:43:54.745+0000] {processor.py:186} INFO - Started process (PID=293) to work on /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:43:54.745+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lstm_refactored_dag.py for tasks to queue
[2025-04-28T19:43:54.747+0000] {logging_mixin.py:190} INFO - [2025-04-28T19:43:54.747+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:43:54.750+0000] {logging_mixin.py:190} INFO - [2025-04-28T19:43:54.749+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/lstm_refactored_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/lstm_refactored_dag.py", line 11, in <module>
    from src.utils.db_utils import setup_database
ModuleNotFoundError: No module named 'src'
[2025-04-28T19:43:54.750+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:43:54.761+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lstm_refactored_dag.py took 0.020 seconds
[2025-04-28T19:44:25.116+0000] {processor.py:186} INFO - Started process (PID=306) to work on /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:44:25.116+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lstm_refactored_dag.py for tasks to queue
[2025-04-28T19:44:25.118+0000] {logging_mixin.py:190} INFO - [2025-04-28T19:44:25.118+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:44:25.121+0000] {logging_mixin.py:190} INFO - [2025-04-28T19:44:25.120+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/lstm_refactored_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/lstm_refactored_dag.py", line 11, in <module>
    from src.utils.db_utils import setup_database
ModuleNotFoundError: No module named 'src'
[2025-04-28T19:44:25.121+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:44:25.135+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lstm_refactored_dag.py took 0.023 seconds
[2025-04-28T19:44:55.492+0000] {processor.py:186} INFO - Started process (PID=311) to work on /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:44:55.492+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lstm_refactored_dag.py for tasks to queue
[2025-04-28T19:44:55.494+0000] {logging_mixin.py:190} INFO - [2025-04-28T19:44:55.494+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:44:55.497+0000] {logging_mixin.py:190} INFO - [2025-04-28T19:44:55.497+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/lstm_refactored_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/lstm_refactored_dag.py", line 11, in <module>
    from src.utils.db_utils import setup_database
ModuleNotFoundError: No module named 'src'
[2025-04-28T19:44:55.498+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:44:55.511+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lstm_refactored_dag.py took 0.023 seconds
[2025-04-28T19:45:25.895+0000] {processor.py:186} INFO - Started process (PID=324) to work on /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:45:25.896+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lstm_refactored_dag.py for tasks to queue
[2025-04-28T19:45:25.897+0000] {logging_mixin.py:190} INFO - [2025-04-28T19:45:25.897+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:45:25.900+0000] {logging_mixin.py:190} INFO - [2025-04-28T19:45:25.899+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/lstm_refactored_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/lstm_refactored_dag.py", line 11, in <module>
    from src.utils.db_utils import setup_database
ModuleNotFoundError: No module named 'src'
[2025-04-28T19:45:25.900+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:45:25.914+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lstm_refactored_dag.py took 0.022 seconds
[2025-04-28T19:45:56.284+0000] {processor.py:186} INFO - Started process (PID=329) to work on /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:45:56.285+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lstm_refactored_dag.py for tasks to queue
[2025-04-28T19:45:56.286+0000] {logging_mixin.py:190} INFO - [2025-04-28T19:45:56.286+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:45:56.289+0000] {logging_mixin.py:190} INFO - [2025-04-28T19:45:56.288+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/lstm_refactored_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/lstm_refactored_dag.py", line 11, in <module>
    from src.utils.db_utils import setup_database
ModuleNotFoundError: No module named 'src'
[2025-04-28T19:45:56.289+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:45:56.300+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lstm_refactored_dag.py took 0.020 seconds
[2025-04-28T19:46:26.667+0000] {processor.py:186} INFO - Started process (PID=342) to work on /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:46:26.668+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lstm_refactored_dag.py for tasks to queue
[2025-04-28T19:46:26.670+0000] {logging_mixin.py:190} INFO - [2025-04-28T19:46:26.670+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:46:26.676+0000] {logging_mixin.py:190} INFO - [2025-04-28T19:46:26.674+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/lstm_refactored_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/lstm_refactored_dag.py", line 11, in <module>
    from src.utils.db_utils import setup_database
ModuleNotFoundError: No module named 'src'
[2025-04-28T19:46:26.677+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:46:26.701+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lstm_refactored_dag.py took 0.038 seconds
[2025-04-28T19:46:57.027+0000] {processor.py:186} INFO - Started process (PID=347) to work on /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:46:57.027+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lstm_refactored_dag.py for tasks to queue
[2025-04-28T19:46:57.029+0000] {logging_mixin.py:190} INFO - [2025-04-28T19:46:57.029+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:46:57.032+0000] {logging_mixin.py:190} INFO - [2025-04-28T19:46:57.031+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/lstm_refactored_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/lstm_refactored_dag.py", line 11, in <module>
    from src.utils.db_utils import setup_database
ModuleNotFoundError: No module named 'src'
[2025-04-28T19:46:57.032+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:46:57.044+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lstm_refactored_dag.py took 0.021 seconds
[2025-04-28T19:47:27.428+0000] {processor.py:186} INFO - Started process (PID=360) to work on /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:47:27.429+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lstm_refactored_dag.py for tasks to queue
[2025-04-28T19:47:27.431+0000] {logging_mixin.py:190} INFO - [2025-04-28T19:47:27.431+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:47:27.434+0000] {logging_mixin.py:190} INFO - [2025-04-28T19:47:27.433+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/lstm_refactored_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/lstm_refactored_dag.py", line 11, in <module>
    from src.utils.db_utils import setup_database
ModuleNotFoundError: No module named 'src'
[2025-04-28T19:47:27.434+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:47:27.446+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lstm_refactored_dag.py took 0.021 seconds
[2025-04-28T19:47:57.845+0000] {processor.py:186} INFO - Started process (PID=365) to work on /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:47:57.845+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lstm_refactored_dag.py for tasks to queue
[2025-04-28T19:47:57.847+0000] {logging_mixin.py:190} INFO - [2025-04-28T19:47:57.847+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:47:57.849+0000] {logging_mixin.py:190} INFO - [2025-04-28T19:47:57.849+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/lstm_refactored_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/lstm_refactored_dag.py", line 11, in <module>
    from src.utils.db_utils import setup_database
ModuleNotFoundError: No module named 'src'
[2025-04-28T19:47:57.850+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:47:57.863+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lstm_refactored_dag.py took 0.022 seconds
[2025-04-28T19:48:28.248+0000] {processor.py:186} INFO - Started process (PID=378) to work on /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:48:28.248+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lstm_refactored_dag.py for tasks to queue
[2025-04-28T19:48:28.249+0000] {logging_mixin.py:190} INFO - [2025-04-28T19:48:28.249+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:48:28.252+0000] {logging_mixin.py:190} INFO - [2025-04-28T19:48:28.252+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/lstm_refactored_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/lstm_refactored_dag.py", line 11, in <module>
    from src.utils.db_utils import setup_database
ModuleNotFoundError: No module named 'src'
[2025-04-28T19:48:28.253+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:48:28.266+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lstm_refactored_dag.py took 0.022 seconds
[2025-04-28T19:48:58.656+0000] {processor.py:186} INFO - Started process (PID=383) to work on /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:48:58.656+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lstm_refactored_dag.py for tasks to queue
[2025-04-28T19:48:58.658+0000] {logging_mixin.py:190} INFO - [2025-04-28T19:48:58.658+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:48:58.661+0000] {logging_mixin.py:190} INFO - [2025-04-28T19:48:58.660+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/lstm_refactored_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/lstm_refactored_dag.py", line 11, in <module>
    from src.utils.db_utils import setup_database
ModuleNotFoundError: No module named 'src'
[2025-04-28T19:48:58.662+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:48:58.678+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lstm_refactored_dag.py took 0.027 seconds
[2025-04-28T19:49:29.040+0000] {processor.py:186} INFO - Started process (PID=395) to work on /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:49:29.040+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lstm_refactored_dag.py for tasks to queue
[2025-04-28T19:49:29.042+0000] {logging_mixin.py:190} INFO - [2025-04-28T19:49:29.041+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:49:29.045+0000] {logging_mixin.py:190} INFO - [2025-04-28T19:49:29.044+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/lstm_refactored_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/lstm_refactored_dag.py", line 11, in <module>
    from src.utils.db_utils import setup_database
ModuleNotFoundError: No module named 'src'
[2025-04-28T19:49:29.045+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:49:29.056+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lstm_refactored_dag.py took 0.021 seconds
[2025-04-28T19:49:59.473+0000] {processor.py:186} INFO - Started process (PID=401) to work on /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:49:59.474+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lstm_refactored_dag.py for tasks to queue
[2025-04-28T19:49:59.476+0000] {logging_mixin.py:190} INFO - [2025-04-28T19:49:59.475+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:49:59.480+0000] {logging_mixin.py:190} INFO - [2025-04-28T19:49:59.479+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/lstm_refactored_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/lstm_refactored_dag.py", line 11, in <module>
    from src.utils.db_utils import setup_database
ModuleNotFoundError: No module named 'src'
[2025-04-28T19:49:59.480+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:49:59.492+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lstm_refactored_dag.py took 0.027 seconds
[2025-04-28T19:50:29.830+0000] {processor.py:186} INFO - Started process (PID=406) to work on /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:50:29.830+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lstm_refactored_dag.py for tasks to queue
[2025-04-28T19:50:29.832+0000] {logging_mixin.py:190} INFO - [2025-04-28T19:50:29.831+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:50:29.834+0000] {logging_mixin.py:190} INFO - [2025-04-28T19:50:29.834+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/lstm_refactored_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/lstm_refactored_dag.py", line 11, in <module>
    from src.utils.db_utils import setup_database
ModuleNotFoundError: No module named 'src'
[2025-04-28T19:50:29.835+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:50:29.846+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lstm_refactored_dag.py took 0.021 seconds
[2025-04-28T19:51:00.252+0000] {processor.py:186} INFO - Started process (PID=419) to work on /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:51:00.253+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lstm_refactored_dag.py for tasks to queue
[2025-04-28T19:51:00.255+0000] {logging_mixin.py:190} INFO - [2025-04-28T19:51:00.255+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:51:00.258+0000] {logging_mixin.py:190} INFO - [2025-04-28T19:51:00.257+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/lstm_refactored_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/lstm_refactored_dag.py", line 11, in <module>
    from src.utils.db_utils import setup_database
ModuleNotFoundError: No module named 'src'
[2025-04-28T19:51:00.258+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:51:00.270+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lstm_refactored_dag.py took 0.022 seconds
[2025-04-28T19:51:30.668+0000] {processor.py:186} INFO - Started process (PID=424) to work on /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:51:30.669+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lstm_refactored_dag.py for tasks to queue
[2025-04-28T19:51:30.670+0000] {logging_mixin.py:190} INFO - [2025-04-28T19:51:30.670+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:51:30.674+0000] {logging_mixin.py:190} INFO - [2025-04-28T19:51:30.673+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/lstm_refactored_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/lstm_refactored_dag.py", line 11, in <module>
    from src.utils.db_utils import setup_database
ModuleNotFoundError: No module named 'src'
[2025-04-28T19:51:30.674+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:51:30.689+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lstm_refactored_dag.py took 0.027 seconds
[2025-04-28T19:52:01.057+0000] {processor.py:186} INFO - Started process (PID=437) to work on /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:52:01.057+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lstm_refactored_dag.py for tasks to queue
[2025-04-28T19:52:01.059+0000] {logging_mixin.py:190} INFO - [2025-04-28T19:52:01.059+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:52:01.062+0000] {logging_mixin.py:190} INFO - [2025-04-28T19:52:01.061+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/lstm_refactored_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/lstm_refactored_dag.py", line 11, in <module>
    from src.utils.db_utils import setup_database
ModuleNotFoundError: No module named 'src'
[2025-04-28T19:52:01.062+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:52:01.075+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lstm_refactored_dag.py took 0.022 seconds
[2025-04-28T19:52:31.478+0000] {processor.py:186} INFO - Started process (PID=442) to work on /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:52:31.479+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lstm_refactored_dag.py for tasks to queue
[2025-04-28T19:52:31.480+0000] {logging_mixin.py:190} INFO - [2025-04-28T19:52:31.480+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:52:31.483+0000] {logging_mixin.py:190} INFO - [2025-04-28T19:52:31.482+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/lstm_refactored_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/lstm_refactored_dag.py", line 11, in <module>
    from src.utils.db_utils import setup_database
ModuleNotFoundError: No module named 'src'
[2025-04-28T19:52:31.483+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:52:31.497+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lstm_refactored_dag.py took 0.022 seconds
[2025-04-28T19:53:01.890+0000] {processor.py:186} INFO - Started process (PID=455) to work on /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:53:01.892+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lstm_refactored_dag.py for tasks to queue
[2025-04-28T19:53:01.893+0000] {logging_mixin.py:190} INFO - [2025-04-28T19:53:01.893+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:53:01.896+0000] {logging_mixin.py:190} INFO - [2025-04-28T19:53:01.895+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/lstm_refactored_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/lstm_refactored_dag.py", line 11, in <module>
    from src.utils.db_utils import setup_database
ModuleNotFoundError: No module named 'src'
[2025-04-28T19:53:01.896+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:53:01.907+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lstm_refactored_dag.py took 0.021 seconds
[2025-04-28T19:53:32.318+0000] {processor.py:186} INFO - Started process (PID=460) to work on /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:53:32.319+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lstm_refactored_dag.py for tasks to queue
[2025-04-28T19:53:32.321+0000] {logging_mixin.py:190} INFO - [2025-04-28T19:53:32.321+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:53:32.324+0000] {logging_mixin.py:190} INFO - [2025-04-28T19:53:32.323+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/lstm_refactored_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/lstm_refactored_dag.py", line 11, in <module>
    from src.utils.db_utils import setup_database
ModuleNotFoundError: No module named 'src'
[2025-04-28T19:53:32.324+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:53:32.336+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lstm_refactored_dag.py took 0.024 seconds
[2025-04-28T19:54:02.702+0000] {processor.py:186} INFO - Started process (PID=473) to work on /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:54:02.702+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lstm_refactored_dag.py for tasks to queue
[2025-04-28T19:54:02.705+0000] {logging_mixin.py:190} INFO - [2025-04-28T19:54:02.705+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:54:02.711+0000] {logging_mixin.py:190} INFO - [2025-04-28T19:54:02.709+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/lstm_refactored_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/lstm_refactored_dag.py", line 11, in <module>
    from src.utils.db_utils import setup_database
ModuleNotFoundError: No module named 'src'
[2025-04-28T19:54:02.712+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:54:02.731+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lstm_refactored_dag.py took 0.038 seconds
[2025-04-28T19:54:33.081+0000] {processor.py:186} INFO - Started process (PID=478) to work on /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:54:33.082+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lstm_refactored_dag.py for tasks to queue
[2025-04-28T19:54:33.083+0000] {logging_mixin.py:190} INFO - [2025-04-28T19:54:33.083+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:54:33.087+0000] {logging_mixin.py:190} INFO - [2025-04-28T19:54:33.086+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/lstm_refactored_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/lstm_refactored_dag.py", line 11, in <module>
    from src.utils.db_utils import setup_database
ModuleNotFoundError: No module named 'src'
[2025-04-28T19:54:33.087+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:54:33.098+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lstm_refactored_dag.py took 0.022 seconds
[2025-04-28T19:55:03.465+0000] {processor.py:186} INFO - Started process (PID=491) to work on /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:55:03.465+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lstm_refactored_dag.py for tasks to queue
[2025-04-28T19:55:03.467+0000] {logging_mixin.py:190} INFO - [2025-04-28T19:55:03.467+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:55:03.471+0000] {logging_mixin.py:190} INFO - [2025-04-28T19:55:03.470+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/lstm_refactored_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/lstm_refactored_dag.py", line 11, in <module>
    from src.utils.db_utils import setup_database
ModuleNotFoundError: No module named 'src'
[2025-04-28T19:55:03.471+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:55:03.482+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lstm_refactored_dag.py took 0.023 seconds
[2025-04-28T19:55:33.857+0000] {processor.py:186} INFO - Started process (PID=496) to work on /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:55:33.858+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lstm_refactored_dag.py for tasks to queue
[2025-04-28T19:55:33.859+0000] {logging_mixin.py:190} INFO - [2025-04-28T19:55:33.859+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:55:33.862+0000] {logging_mixin.py:190} INFO - [2025-04-28T19:55:33.861+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/lstm_refactored_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/lstm_refactored_dag.py", line 11, in <module>
    from src.utils.db_utils import setup_database
ModuleNotFoundError: No module named 'src'
[2025-04-28T19:55:33.862+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:55:33.873+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lstm_refactored_dag.py took 0.020 seconds
[2025-04-28T19:56:04.176+0000] {processor.py:186} INFO - Started process (PID=509) to work on /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:56:04.176+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lstm_refactored_dag.py for tasks to queue
[2025-04-28T19:56:04.178+0000] {logging_mixin.py:190} INFO - [2025-04-28T19:56:04.178+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:56:04.181+0000] {logging_mixin.py:190} INFO - [2025-04-28T19:56:04.180+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/lstm_refactored_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/lstm_refactored_dag.py", line 11, in <module>
    from src.utils.db_utils import setup_database
ModuleNotFoundError: No module named 'src'
[2025-04-28T19:56:04.182+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:56:04.197+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lstm_refactored_dag.py took 0.025 seconds
[2025-04-28T19:56:34.556+0000] {processor.py:186} INFO - Started process (PID=514) to work on /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:56:34.556+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lstm_refactored_dag.py for tasks to queue
[2025-04-28T19:56:34.558+0000] {logging_mixin.py:190} INFO - [2025-04-28T19:56:34.558+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:56:34.561+0000] {logging_mixin.py:190} INFO - [2025-04-28T19:56:34.560+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/lstm_refactored_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/lstm_refactored_dag.py", line 11, in <module>
    from src.utils.db_utils import setup_database
ModuleNotFoundError: No module named 'src'
[2025-04-28T19:56:34.562+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:56:34.573+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lstm_refactored_dag.py took 0.023 seconds
[2025-04-28T19:57:04.923+0000] {processor.py:186} INFO - Started process (PID=527) to work on /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:57:04.924+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lstm_refactored_dag.py for tasks to queue
[2025-04-28T19:57:04.925+0000] {logging_mixin.py:190} INFO - [2025-04-28T19:57:04.925+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:57:04.928+0000] {logging_mixin.py:190} INFO - [2025-04-28T19:57:04.928+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/lstm_refactored_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/lstm_refactored_dag.py", line 11, in <module>
    from src.utils.db_utils import setup_database
ModuleNotFoundError: No module named 'src'
[2025-04-28T19:57:04.929+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:57:04.940+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lstm_refactored_dag.py took 0.022 seconds
[2025-04-28T19:57:35.306+0000] {processor.py:186} INFO - Started process (PID=532) to work on /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:57:35.307+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lstm_refactored_dag.py for tasks to queue
[2025-04-28T19:57:35.309+0000] {logging_mixin.py:190} INFO - [2025-04-28T19:57:35.308+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:57:35.314+0000] {logging_mixin.py:190} INFO - [2025-04-28T19:57:35.313+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/lstm_refactored_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/lstm_refactored_dag.py", line 11, in <module>
    from src.utils.db_utils import setup_database
ModuleNotFoundError: No module named 'src'
[2025-04-28T19:57:35.315+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:57:35.330+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lstm_refactored_dag.py took 0.031 seconds
[2025-04-28T19:58:05.672+0000] {processor.py:186} INFO - Started process (PID=545) to work on /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:58:05.672+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lstm_refactored_dag.py for tasks to queue
[2025-04-28T19:58:05.674+0000] {logging_mixin.py:190} INFO - [2025-04-28T19:58:05.674+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:58:05.677+0000] {logging_mixin.py:190} INFO - [2025-04-28T19:58:05.676+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/lstm_refactored_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/lstm_refactored_dag.py", line 11, in <module>
    from src.utils.db_utils import setup_database
ModuleNotFoundError: No module named 'src'
[2025-04-28T19:58:05.678+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:58:05.688+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lstm_refactored_dag.py took 0.020 seconds
[2025-04-28T19:58:36.076+0000] {processor.py:186} INFO - Started process (PID=550) to work on /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:58:36.077+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lstm_refactored_dag.py for tasks to queue
[2025-04-28T19:58:36.079+0000] {logging_mixin.py:190} INFO - [2025-04-28T19:58:36.079+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:58:36.082+0000] {logging_mixin.py:190} INFO - [2025-04-28T19:58:36.081+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/lstm_refactored_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/lstm_refactored_dag.py", line 11, in <module>
    from src.utils.db_utils import setup_database
ModuleNotFoundError: No module named 'src'
[2025-04-28T19:58:36.082+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:58:36.098+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lstm_refactored_dag.py took 0.026 seconds
[2025-04-28T19:59:06.458+0000] {processor.py:186} INFO - Started process (PID=563) to work on /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:59:06.459+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lstm_refactored_dag.py for tasks to queue
[2025-04-28T19:59:06.461+0000] {logging_mixin.py:190} INFO - [2025-04-28T19:59:06.460+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:59:06.464+0000] {logging_mixin.py:190} INFO - [2025-04-28T19:59:06.463+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/lstm_refactored_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/lstm_refactored_dag.py", line 11, in <module>
    from src.utils.db_utils import setup_database
ModuleNotFoundError: No module named 'src'
[2025-04-28T19:59:06.464+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:59:06.478+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lstm_refactored_dag.py took 0.026 seconds
[2025-04-28T19:59:36.841+0000] {processor.py:186} INFO - Started process (PID=568) to work on /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:59:36.841+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lstm_refactored_dag.py for tasks to queue
[2025-04-28T19:59:36.843+0000] {logging_mixin.py:190} INFO - [2025-04-28T19:59:36.843+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:59:36.846+0000] {logging_mixin.py:190} INFO - [2025-04-28T19:59:36.845+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/lstm_refactored_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/lstm_refactored_dag.py", line 11, in <module>
    from src.utils.db_utils import setup_database
ModuleNotFoundError: No module named 'src'
[2025-04-28T19:59:36.847+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T19:59:36.858+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lstm_refactored_dag.py took 0.021 seconds
[2025-04-28T20:00:07.231+0000] {processor.py:186} INFO - Started process (PID=581) to work on /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:00:07.232+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lstm_refactored_dag.py for tasks to queue
[2025-04-28T20:00:07.234+0000] {logging_mixin.py:190} INFO - [2025-04-28T20:00:07.233+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:00:07.237+0000] {logging_mixin.py:190} INFO - [2025-04-28T20:00:07.236+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/lstm_refactored_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/lstm_refactored_dag.py", line 11, in <module>
    from src.utils.db_utils import setup_database
ModuleNotFoundError: No module named 'src'
[2025-04-28T20:00:07.237+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:00:07.248+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lstm_refactored_dag.py took 0.021 seconds
[2025-04-28T20:00:37.648+0000] {processor.py:186} INFO - Started process (PID=586) to work on /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:00:37.649+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lstm_refactored_dag.py for tasks to queue
[2025-04-28T20:00:37.650+0000] {logging_mixin.py:190} INFO - [2025-04-28T20:00:37.650+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:00:37.653+0000] {logging_mixin.py:190} INFO - [2025-04-28T20:00:37.652+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/lstm_refactored_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/lstm_refactored_dag.py", line 11, in <module>
    from src.utils.db_utils import setup_database
ModuleNotFoundError: No module named 'src'
[2025-04-28T20:00:37.653+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:00:37.673+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lstm_refactored_dag.py took 0.033 seconds
[2025-04-28T20:01:08.004+0000] {processor.py:186} INFO - Started process (PID=599) to work on /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:01:08.005+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lstm_refactored_dag.py for tasks to queue
[2025-04-28T20:01:08.006+0000] {logging_mixin.py:190} INFO - [2025-04-28T20:01:08.006+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:01:08.009+0000] {logging_mixin.py:190} INFO - [2025-04-28T20:01:08.008+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/lstm_refactored_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/lstm_refactored_dag.py", line 11, in <module>
    from src.utils.db_utils import setup_database
ModuleNotFoundError: No module named 'src'
[2025-04-28T20:01:08.009+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:01:08.022+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lstm_refactored_dag.py took 0.022 seconds
[2025-04-28T20:01:38.433+0000] {processor.py:186} INFO - Started process (PID=604) to work on /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:01:38.434+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lstm_refactored_dag.py for tasks to queue
[2025-04-28T20:01:38.435+0000] {logging_mixin.py:190} INFO - [2025-04-28T20:01:38.435+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:01:38.438+0000] {logging_mixin.py:190} INFO - [2025-04-28T20:01:38.437+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/lstm_refactored_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/lstm_refactored_dag.py", line 11, in <module>
    from src.utils.db_utils import setup_database
ModuleNotFoundError: No module named 'src'
[2025-04-28T20:01:38.438+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:01:38.449+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lstm_refactored_dag.py took 0.020 seconds
[2025-04-28T20:02:08.805+0000] {processor.py:186} INFO - Started process (PID=617) to work on /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:02:08.806+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lstm_refactored_dag.py for tasks to queue
[2025-04-28T20:02:08.808+0000] {logging_mixin.py:190} INFO - [2025-04-28T20:02:08.807+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:02:08.811+0000] {logging_mixin.py:190} INFO - [2025-04-28T20:02:08.810+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/lstm_refactored_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/lstm_refactored_dag.py", line 11, in <module>
    from src.utils.db_utils import setup_database
ModuleNotFoundError: No module named 'src'
[2025-04-28T20:02:08.811+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:02:08.826+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lstm_refactored_dag.py took 0.028 seconds
[2025-04-28T20:02:39.195+0000] {processor.py:186} INFO - Started process (PID=622) to work on /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:02:39.195+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lstm_refactored_dag.py for tasks to queue
[2025-04-28T20:02:39.197+0000] {logging_mixin.py:190} INFO - [2025-04-28T20:02:39.197+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:02:39.200+0000] {logging_mixin.py:190} INFO - [2025-04-28T20:02:39.199+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/lstm_refactored_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/lstm_refactored_dag.py", line 11, in <module>
    from src.utils.db_utils import setup_database
ModuleNotFoundError: No module named 'src'
[2025-04-28T20:02:39.200+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:02:39.216+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lstm_refactored_dag.py took 0.026 seconds
[2025-04-28T20:03:09.603+0000] {processor.py:186} INFO - Started process (PID=634) to work on /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:03:09.604+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lstm_refactored_dag.py for tasks to queue
[2025-04-28T20:03:09.606+0000] {logging_mixin.py:190} INFO - [2025-04-28T20:03:09.605+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:03:09.610+0000] {logging_mixin.py:190} INFO - [2025-04-28T20:03:09.609+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/lstm_refactored_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/lstm_refactored_dag.py", line 11, in <module>
    from src.utils.db_utils import setup_database
ModuleNotFoundError: No module named 'src'
[2025-04-28T20:03:09.611+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:03:09.627+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lstm_refactored_dag.py took 0.027 seconds
[2025-04-28T20:03:40.023+0000] {processor.py:186} INFO - Started process (PID=639) to work on /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:03:40.024+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lstm_refactored_dag.py for tasks to queue
[2025-04-28T20:03:40.027+0000] {logging_mixin.py:190} INFO - [2025-04-28T20:03:40.027+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:03:40.034+0000] {logging_mixin.py:190} INFO - [2025-04-28T20:03:40.033+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/lstm_refactored_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/lstm_refactored_dag.py", line 11, in <module>
    from src.utils.db_utils import setup_database
ModuleNotFoundError: No module named 'src'
[2025-04-28T20:03:40.035+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:03:40.051+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lstm_refactored_dag.py took 0.037 seconds
[2025-04-28T20:04:10.410+0000] {processor.py:186} INFO - Started process (PID=652) to work on /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:04:10.410+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lstm_refactored_dag.py for tasks to queue
[2025-04-28T20:04:10.411+0000] {logging_mixin.py:190} INFO - [2025-04-28T20:04:10.411+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:04:10.414+0000] {logging_mixin.py:190} INFO - [2025-04-28T20:04:10.413+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/lstm_refactored_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/lstm_refactored_dag.py", line 11, in <module>
    from src.utils.db_utils import setup_database
ModuleNotFoundError: No module named 'src'
[2025-04-28T20:04:10.415+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:04:10.426+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lstm_refactored_dag.py took 0.020 seconds
[2025-04-28T20:04:40.808+0000] {processor.py:186} INFO - Started process (PID=657) to work on /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:04:40.808+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lstm_refactored_dag.py for tasks to queue
[2025-04-28T20:04:40.810+0000] {logging_mixin.py:190} INFO - [2025-04-28T20:04:40.810+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:04:40.813+0000] {logging_mixin.py:190} INFO - [2025-04-28T20:04:40.812+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/lstm_refactored_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/lstm_refactored_dag.py", line 11, in <module>
    from src.utils.db_utils import setup_database
ModuleNotFoundError: No module named 'src'
[2025-04-28T20:04:40.813+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:04:40.827+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lstm_refactored_dag.py took 0.022 seconds
[2025-04-28T20:05:11.234+0000] {processor.py:186} INFO - Started process (PID=669) to work on /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:05:11.234+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lstm_refactored_dag.py for tasks to queue
[2025-04-28T20:05:11.236+0000] {logging_mixin.py:190} INFO - [2025-04-28T20:05:11.236+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:05:11.239+0000] {logging_mixin.py:190} INFO - [2025-04-28T20:05:11.238+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/lstm_refactored_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/lstm_refactored_dag.py", line 11, in <module>
    from src.utils.db_utils import setup_database
ModuleNotFoundError: No module named 'src'
[2025-04-28T20:05:11.239+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:05:11.250+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lstm_refactored_dag.py took 0.020 seconds
[2025-04-28T20:05:41.652+0000] {processor.py:186} INFO - Started process (PID=674) to work on /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:05:41.653+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lstm_refactored_dag.py for tasks to queue
[2025-04-28T20:05:41.655+0000] {logging_mixin.py:190} INFO - [2025-04-28T20:05:41.655+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:05:41.658+0000] {logging_mixin.py:190} INFO - [2025-04-28T20:05:41.657+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/lstm_refactored_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/lstm_refactored_dag.py", line 11, in <module>
    from src.utils.db_utils import setup_database
ModuleNotFoundError: No module named 'src'
[2025-04-28T20:05:41.658+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:05:41.669+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lstm_refactored_dag.py took 0.024 seconds
[2025-04-28T20:06:12.032+0000] {processor.py:186} INFO - Started process (PID=687) to work on /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:06:12.033+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lstm_refactored_dag.py for tasks to queue
[2025-04-28T20:06:12.034+0000] {logging_mixin.py:190} INFO - [2025-04-28T20:06:12.034+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:06:12.037+0000] {logging_mixin.py:190} INFO - [2025-04-28T20:06:12.036+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/lstm_refactored_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/lstm_refactored_dag.py", line 11, in <module>
    from src.utils.db_utils import setup_database
ModuleNotFoundError: No module named 'src'
[2025-04-28T20:06:12.037+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:06:12.051+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lstm_refactored_dag.py took 0.023 seconds
[2025-04-28T20:06:42.432+0000] {processor.py:186} INFO - Started process (PID=692) to work on /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:06:42.432+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lstm_refactored_dag.py for tasks to queue
[2025-04-28T20:06:42.435+0000] {logging_mixin.py:190} INFO - [2025-04-28T20:06:42.434+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:06:42.438+0000] {logging_mixin.py:190} INFO - [2025-04-28T20:06:42.437+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/lstm_refactored_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/lstm_refactored_dag.py", line 11, in <module>
    from src.utils.db_utils import setup_database
ModuleNotFoundError: No module named 'src'
[2025-04-28T20:06:42.438+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:06:42.449+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lstm_refactored_dag.py took 0.024 seconds
[2025-04-28T20:07:12.856+0000] {processor.py:186} INFO - Started process (PID=705) to work on /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:07:12.857+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lstm_refactored_dag.py for tasks to queue
[2025-04-28T20:07:12.858+0000] {logging_mixin.py:190} INFO - [2025-04-28T20:07:12.858+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:07:12.861+0000] {logging_mixin.py:190} INFO - [2025-04-28T20:07:12.860+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/lstm_refactored_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/lstm_refactored_dag.py", line 11, in <module>
    from src.utils.db_utils import setup_database
ModuleNotFoundError: No module named 'src'
[2025-04-28T20:07:12.862+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:07:12.878+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lstm_refactored_dag.py took 0.026 seconds
[2025-04-28T20:07:43.296+0000] {processor.py:186} INFO - Started process (PID=710) to work on /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:07:43.297+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lstm_refactored_dag.py for tasks to queue
[2025-04-28T20:07:43.300+0000] {logging_mixin.py:190} INFO - [2025-04-28T20:07:43.299+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:07:43.308+0000] {logging_mixin.py:190} INFO - [2025-04-28T20:07:43.305+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/lstm_refactored_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/lstm_refactored_dag.py", line 11, in <module>
    from src.utils.db_utils import setup_database
ModuleNotFoundError: No module named 'src'
[2025-04-28T20:07:43.309+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:07:43.329+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lstm_refactored_dag.py took 0.040 seconds
[2025-04-28T20:08:13.693+0000] {processor.py:186} INFO - Started process (PID=723) to work on /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:08:13.693+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lstm_refactored_dag.py for tasks to queue
[2025-04-28T20:08:13.694+0000] {logging_mixin.py:190} INFO - [2025-04-28T20:08:13.694+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:08:13.697+0000] {logging_mixin.py:190} INFO - [2025-04-28T20:08:13.696+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/lstm_refactored_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/lstm_refactored_dag.py", line 11, in <module>
    from src.utils.db_utils import setup_database
ModuleNotFoundError: No module named 'src'
[2025-04-28T20:08:13.698+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:08:13.709+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lstm_refactored_dag.py took 0.020 seconds
[2025-04-28T20:08:44.084+0000] {processor.py:186} INFO - Started process (PID=728) to work on /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:08:44.084+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lstm_refactored_dag.py for tasks to queue
[2025-04-28T20:08:44.087+0000] {logging_mixin.py:190} INFO - [2025-04-28T20:08:44.086+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:08:44.090+0000] {logging_mixin.py:190} INFO - [2025-04-28T20:08:44.089+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/lstm_refactored_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/lstm_refactored_dag.py", line 11, in <module>
    from src.utils.db_utils import setup_database
ModuleNotFoundError: No module named 'src'
[2025-04-28T20:08:44.090+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:08:44.102+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lstm_refactored_dag.py took 0.024 seconds
[2025-04-28T20:09:14.481+0000] {processor.py:186} INFO - Started process (PID=741) to work on /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:09:14.482+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lstm_refactored_dag.py for tasks to queue
[2025-04-28T20:09:14.484+0000] {logging_mixin.py:190} INFO - [2025-04-28T20:09:14.484+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:09:14.491+0000] {logging_mixin.py:190} INFO - [2025-04-28T20:09:14.489+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/lstm_refactored_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/lstm_refactored_dag.py", line 11, in <module>
    from src.utils.db_utils import setup_database
ModuleNotFoundError: No module named 'src'
[2025-04-28T20:09:14.491+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:09:14.511+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lstm_refactored_dag.py took 0.038 seconds
[2025-04-28T20:09:44.895+0000] {processor.py:186} INFO - Started process (PID=746) to work on /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:09:44.895+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lstm_refactored_dag.py for tasks to queue
[2025-04-28T20:09:44.897+0000] {logging_mixin.py:190} INFO - [2025-04-28T20:09:44.897+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:09:44.900+0000] {logging_mixin.py:190} INFO - [2025-04-28T20:09:44.900+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/lstm_refactored_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/lstm_refactored_dag.py", line 11, in <module>
    from src.utils.db_utils import setup_database
ModuleNotFoundError: No module named 'src'
[2025-04-28T20:09:44.901+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:09:44.911+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lstm_refactored_dag.py took 0.021 seconds
[2025-04-28T20:10:15.281+0000] {processor.py:186} INFO - Started process (PID=759) to work on /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:10:15.282+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lstm_refactored_dag.py for tasks to queue
[2025-04-28T20:10:15.284+0000] {logging_mixin.py:190} INFO - [2025-04-28T20:10:15.283+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:10:15.287+0000] {logging_mixin.py:190} INFO - [2025-04-28T20:10:15.286+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/lstm_refactored_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/lstm_refactored_dag.py", line 11, in <module>
    from src.utils.db_utils import setup_database
ModuleNotFoundError: No module named 'src'
[2025-04-28T20:10:15.287+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:10:15.299+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lstm_refactored_dag.py took 0.021 seconds
[2025-04-28T20:10:45.692+0000] {processor.py:186} INFO - Started process (PID=764) to work on /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:10:45.693+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lstm_refactored_dag.py for tasks to queue
[2025-04-28T20:10:45.694+0000] {logging_mixin.py:190} INFO - [2025-04-28T20:10:45.694+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:10:45.697+0000] {logging_mixin.py:190} INFO - [2025-04-28T20:10:45.696+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/lstm_refactored_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/lstm_refactored_dag.py", line 11, in <module>
    from src.utils.db_utils import setup_database
ModuleNotFoundError: No module named 'src'
[2025-04-28T20:10:45.697+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:10:45.711+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lstm_refactored_dag.py took 0.022 seconds
[2025-04-28T20:11:16.059+0000] {processor.py:186} INFO - Started process (PID=777) to work on /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:11:16.059+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lstm_refactored_dag.py for tasks to queue
[2025-04-28T20:11:16.061+0000] {logging_mixin.py:190} INFO - [2025-04-28T20:11:16.060+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:11:16.063+0000] {logging_mixin.py:190} INFO - [2025-04-28T20:11:16.063+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/lstm_refactored_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/lstm_refactored_dag.py", line 11, in <module>
    from src.utils.db_utils import setup_database
ModuleNotFoundError: No module named 'src'
[2025-04-28T20:11:16.064+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:11:16.076+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lstm_refactored_dag.py took 0.021 seconds
[2025-04-28T20:11:46.476+0000] {processor.py:186} INFO - Started process (PID=782) to work on /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:11:46.477+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lstm_refactored_dag.py for tasks to queue
[2025-04-28T20:11:46.481+0000] {logging_mixin.py:190} INFO - [2025-04-28T20:11:46.481+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:11:46.489+0000] {logging_mixin.py:190} INFO - [2025-04-28T20:11:46.487+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/lstm_refactored_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/lstm_refactored_dag.py", line 11, in <module>
    from src.utils.db_utils import setup_database
ModuleNotFoundError: No module named 'src'
[2025-04-28T20:11:46.489+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:11:46.507+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lstm_refactored_dag.py took 0.038 seconds
[2025-04-28T20:12:16.849+0000] {processor.py:186} INFO - Started process (PID=795) to work on /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:12:16.850+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lstm_refactored_dag.py for tasks to queue
[2025-04-28T20:12:16.851+0000] {logging_mixin.py:190} INFO - [2025-04-28T20:12:16.851+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:12:16.854+0000] {logging_mixin.py:190} INFO - [2025-04-28T20:12:16.853+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/lstm_refactored_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/lstm_refactored_dag.py", line 11, in <module>
    from src.utils.db_utils import setup_database
ModuleNotFoundError: No module named 'src'
[2025-04-28T20:12:16.854+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:12:16.866+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lstm_refactored_dag.py took 0.020 seconds
[2025-04-28T20:12:47.245+0000] {processor.py:186} INFO - Started process (PID=800) to work on /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:12:47.245+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lstm_refactored_dag.py for tasks to queue
[2025-04-28T20:12:47.248+0000] {logging_mixin.py:190} INFO - [2025-04-28T20:12:47.247+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:12:47.253+0000] {logging_mixin.py:190} INFO - [2025-04-28T20:12:47.251+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/lstm_refactored_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/lstm_refactored_dag.py", line 11, in <module>
    from src.utils.db_utils import setup_database
ModuleNotFoundError: No module named 'src'
[2025-04-28T20:12:47.253+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:12:47.272+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lstm_refactored_dag.py took 0.032 seconds
[2025-04-28T20:13:17.627+0000] {processor.py:186} INFO - Started process (PID=813) to work on /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:13:17.627+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lstm_refactored_dag.py for tasks to queue
[2025-04-28T20:13:17.629+0000] {logging_mixin.py:190} INFO - [2025-04-28T20:13:17.629+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:13:17.632+0000] {logging_mixin.py:190} INFO - [2025-04-28T20:13:17.631+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/lstm_refactored_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/lstm_refactored_dag.py", line 11, in <module>
    from src.utils.db_utils import setup_database
ModuleNotFoundError: No module named 'src'
[2025-04-28T20:13:17.633+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:13:17.646+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lstm_refactored_dag.py took 0.023 seconds
[2025-04-28T20:13:47.996+0000] {processor.py:186} INFO - Started process (PID=818) to work on /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:13:47.997+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lstm_refactored_dag.py for tasks to queue
[2025-04-28T20:13:48.000+0000] {logging_mixin.py:190} INFO - [2025-04-28T20:13:48.000+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:13:48.006+0000] {logging_mixin.py:190} INFO - [2025-04-28T20:13:48.005+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/lstm_refactored_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/lstm_refactored_dag.py", line 11, in <module>
    from src.utils.db_utils import setup_database
ModuleNotFoundError: No module named 'src'
[2025-04-28T20:13:48.007+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:13:48.030+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lstm_refactored_dag.py took 0.038 seconds
[2025-04-28T20:14:18.416+0000] {processor.py:186} INFO - Started process (PID=831) to work on /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:14:18.416+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lstm_refactored_dag.py for tasks to queue
[2025-04-28T20:14:18.418+0000] {logging_mixin.py:190} INFO - [2025-04-28T20:14:18.417+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:14:18.420+0000] {logging_mixin.py:190} INFO - [2025-04-28T20:14:18.420+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/lstm_refactored_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/lstm_refactored_dag.py", line 11, in <module>
    from src.utils.db_utils import setup_database
ModuleNotFoundError: No module named 'src'
[2025-04-28T20:14:18.421+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:14:18.432+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lstm_refactored_dag.py took 0.020 seconds
[2025-04-28T20:14:48.803+0000] {processor.py:186} INFO - Started process (PID=836) to work on /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:14:48.804+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lstm_refactored_dag.py for tasks to queue
[2025-04-28T20:14:48.805+0000] {logging_mixin.py:190} INFO - [2025-04-28T20:14:48.805+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:14:48.808+0000] {logging_mixin.py:190} INFO - [2025-04-28T20:14:48.807+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/lstm_refactored_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/lstm_refactored_dag.py", line 11, in <module>
    from src.utils.db_utils import setup_database
ModuleNotFoundError: No module named 'src'
[2025-04-28T20:14:48.809+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:14:48.820+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lstm_refactored_dag.py took 0.021 seconds
[2025-04-28T20:15:19.190+0000] {processor.py:186} INFO - Started process (PID=849) to work on /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:15:19.191+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lstm_refactored_dag.py for tasks to queue
[2025-04-28T20:15:19.193+0000] {logging_mixin.py:190} INFO - [2025-04-28T20:15:19.192+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:15:19.199+0000] {logging_mixin.py:190} INFO - [2025-04-28T20:15:19.197+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/lstm_refactored_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/lstm_refactored_dag.py", line 11, in <module>
    from src.utils.db_utils import setup_database
ModuleNotFoundError: No module named 'src'
[2025-04-28T20:15:19.199+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:15:19.212+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lstm_refactored_dag.py took 0.027 seconds
[2025-04-28T20:15:49.628+0000] {processor.py:186} INFO - Started process (PID=854) to work on /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:15:49.628+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lstm_refactored_dag.py for tasks to queue
[2025-04-28T20:15:49.631+0000] {logging_mixin.py:190} INFO - [2025-04-28T20:15:49.630+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:15:49.636+0000] {logging_mixin.py:190} INFO - [2025-04-28T20:15:49.635+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/lstm_refactored_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/lstm_refactored_dag.py", line 11, in <module>
    from src.utils.db_utils import setup_database
ModuleNotFoundError: No module named 'src'
[2025-04-28T20:15:49.636+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:15:49.651+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lstm_refactored_dag.py took 0.028 seconds
[2025-04-28T20:16:19.997+0000] {processor.py:186} INFO - Started process (PID=867) to work on /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:16:19.997+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lstm_refactored_dag.py for tasks to queue
[2025-04-28T20:16:19.999+0000] {logging_mixin.py:190} INFO - [2025-04-28T20:16:19.998+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:16:20.002+0000] {logging_mixin.py:190} INFO - [2025-04-28T20:16:20.001+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/lstm_refactored_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/lstm_refactored_dag.py", line 11, in <module>
    from src.utils.db_utils import setup_database
ModuleNotFoundError: No module named 'src'
[2025-04-28T20:16:20.002+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:16:20.015+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lstm_refactored_dag.py took 0.022 seconds
[2025-04-28T20:16:50.377+0000] {processor.py:186} INFO - Started process (PID=872) to work on /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:16:50.378+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lstm_refactored_dag.py for tasks to queue
[2025-04-28T20:16:50.379+0000] {logging_mixin.py:190} INFO - [2025-04-28T20:16:50.379+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:16:50.384+0000] {logging_mixin.py:190} INFO - [2025-04-28T20:16:50.383+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/lstm_refactored_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/lstm_refactored_dag.py", line 11, in <module>
    from src.utils.db_utils import setup_database
ModuleNotFoundError: No module named 'src'
[2025-04-28T20:16:50.385+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:16:50.401+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lstm_refactored_dag.py took 0.033 seconds
[2025-04-28T20:17:20.786+0000] {processor.py:186} INFO - Started process (PID=884) to work on /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:17:20.787+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lstm_refactored_dag.py for tasks to queue
[2025-04-28T20:17:20.788+0000] {logging_mixin.py:190} INFO - [2025-04-28T20:17:20.788+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:17:20.791+0000] {logging_mixin.py:190} INFO - [2025-04-28T20:17:20.790+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/lstm_refactored_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/lstm_refactored_dag.py", line 11, in <module>
    from src.utils.db_utils import setup_database
ModuleNotFoundError: No module named 'src'
[2025-04-28T20:17:20.791+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:17:20.803+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lstm_refactored_dag.py took 0.021 seconds
[2025-04-28T20:17:51.230+0000] {processor.py:186} INFO - Started process (PID=889) to work on /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:17:51.230+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lstm_refactored_dag.py for tasks to queue
[2025-04-28T20:17:51.232+0000] {logging_mixin.py:190} INFO - [2025-04-28T20:17:51.231+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:17:51.235+0000] {logging_mixin.py:190} INFO - [2025-04-28T20:17:51.234+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/lstm_refactored_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/lstm_refactored_dag.py", line 11, in <module>
    from src.utils.db_utils import setup_database
ModuleNotFoundError: No module named 'src'
[2025-04-28T20:17:51.235+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:17:51.248+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lstm_refactored_dag.py took 0.023 seconds
[2025-04-28T20:18:21.614+0000] {processor.py:186} INFO - Started process (PID=902) to work on /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:18:21.615+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lstm_refactored_dag.py for tasks to queue
[2025-04-28T20:18:21.616+0000] {logging_mixin.py:190} INFO - [2025-04-28T20:18:21.616+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:18:21.619+0000] {logging_mixin.py:190} INFO - [2025-04-28T20:18:21.618+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/lstm_refactored_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/lstm_refactored_dag.py", line 11, in <module>
    from src.utils.db_utils import setup_database
ModuleNotFoundError: No module named 'src'
[2025-04-28T20:18:21.619+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:18:21.630+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lstm_refactored_dag.py took 0.020 seconds
[2025-04-28T20:18:52.022+0000] {processor.py:186} INFO - Started process (PID=907) to work on /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:18:52.023+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lstm_refactored_dag.py for tasks to queue
[2025-04-28T20:18:52.024+0000] {logging_mixin.py:190} INFO - [2025-04-28T20:18:52.024+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:18:52.027+0000] {logging_mixin.py:190} INFO - [2025-04-28T20:18:52.026+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/lstm_refactored_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/lstm_refactored_dag.py", line 11, in <module>
    from src.utils.db_utils import setup_database
ModuleNotFoundError: No module named 'src'
[2025-04-28T20:18:52.027+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:18:52.041+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lstm_refactored_dag.py took 0.023 seconds
[2025-04-28T20:19:22.434+0000] {processor.py:186} INFO - Started process (PID=920) to work on /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:19:22.435+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lstm_refactored_dag.py for tasks to queue
[2025-04-28T20:19:22.437+0000] {logging_mixin.py:190} INFO - [2025-04-28T20:19:22.436+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:19:22.440+0000] {logging_mixin.py:190} INFO - [2025-04-28T20:19:22.439+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/lstm_refactored_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/lstm_refactored_dag.py", line 11, in <module>
    from src.utils.db_utils import setup_database
ModuleNotFoundError: No module named 'src'
[2025-04-28T20:19:22.440+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:19:22.452+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lstm_refactored_dag.py took 0.021 seconds
[2025-04-28T20:19:52.816+0000] {processor.py:186} INFO - Started process (PID=925) to work on /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:19:52.817+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lstm_refactored_dag.py for tasks to queue
[2025-04-28T20:19:52.820+0000] {logging_mixin.py:190} INFO - [2025-04-28T20:19:52.819+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:19:52.826+0000] {logging_mixin.py:190} INFO - [2025-04-28T20:19:52.824+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/lstm_refactored_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/lstm_refactored_dag.py", line 11, in <module>
    from src.utils.db_utils import setup_database
ModuleNotFoundError: No module named 'src'
[2025-04-28T20:19:52.827+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:19:52.848+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lstm_refactored_dag.py took 0.041 seconds
[2025-04-28T20:20:23.231+0000] {processor.py:186} INFO - Started process (PID=938) to work on /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:20:23.231+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lstm_refactored_dag.py for tasks to queue
[2025-04-28T20:20:23.233+0000] {logging_mixin.py:190} INFO - [2025-04-28T20:20:23.233+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:20:23.236+0000] {logging_mixin.py:190} INFO - [2025-04-28T20:20:23.235+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/lstm_refactored_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/lstm_refactored_dag.py", line 11, in <module>
    from src.utils.db_utils import setup_database
ModuleNotFoundError: No module named 'src'
[2025-04-28T20:20:23.236+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:20:23.256+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lstm_refactored_dag.py took 0.029 seconds
[2025-04-28T20:20:53.656+0000] {processor.py:186} INFO - Started process (PID=943) to work on /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:20:53.657+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lstm_refactored_dag.py for tasks to queue
[2025-04-28T20:20:53.659+0000] {logging_mixin.py:190} INFO - [2025-04-28T20:20:53.659+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:20:53.662+0000] {logging_mixin.py:190} INFO - [2025-04-28T20:20:53.661+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/lstm_refactored_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/lstm_refactored_dag.py", line 11, in <module>
    from src.utils.db_utils import setup_database
ModuleNotFoundError: No module named 'src'
[2025-04-28T20:20:53.662+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:20:53.674+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lstm_refactored_dag.py took 0.023 seconds
[2025-04-28T20:21:24.032+0000] {processor.py:186} INFO - Started process (PID=956) to work on /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:21:24.033+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lstm_refactored_dag.py for tasks to queue
[2025-04-28T20:21:24.035+0000] {logging_mixin.py:190} INFO - [2025-04-28T20:21:24.034+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:21:24.038+0000] {logging_mixin.py:190} INFO - [2025-04-28T20:21:24.037+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/lstm_refactored_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/lstm_refactored_dag.py", line 11, in <module>
    from src.utils.db_utils import setup_database
ModuleNotFoundError: No module named 'src'
[2025-04-28T20:21:24.039+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:21:24.052+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lstm_refactored_dag.py took 0.023 seconds
[2025-04-28T20:21:50.408+0000] {processor.py:186} INFO - Started process (PID=961) to work on /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:21:50.410+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lstm_refactored_dag.py for tasks to queue
[2025-04-28T20:21:50.413+0000] {logging_mixin.py:190} INFO - [2025-04-28T20:21:50.412+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:21:50.422+0000] {logging_mixin.py:190} INFO - [2025-04-28T20:21:50.420+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/lstm_refactored_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/lstm_refactored_dag.py", line 11, in <module>
    from src.utils.db_utils import setup_database
ModuleNotFoundError: No module named 'src'
[2025-04-28T20:21:50.423+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:21:50.439+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lstm_refactored_dag.py took 0.038 seconds
[2025-04-28T20:22:05.653+0000] {processor.py:186} INFO - Started process (PID=966) to work on /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:22:05.654+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lstm_refactored_dag.py for tasks to queue
[2025-04-28T20:22:05.656+0000] {logging_mixin.py:190} INFO - [2025-04-28T20:22:05.656+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:22:05.664+0000] {logging_mixin.py:190} INFO - [2025-04-28T20:22:05.662+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/lstm_refactored_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/lstm_refactored_dag.py", line 11, in <module>
    from src.utils.db_utils import setup_database
ModuleNotFoundError: No module named 'src'
[2025-04-28T20:22:05.665+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:22:05.681+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lstm_refactored_dag.py took 0.036 seconds
[2025-04-28T20:22:23.905+0000] {processor.py:186} INFO - Started process (PID=979) to work on /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:22:23.906+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lstm_refactored_dag.py for tasks to queue
[2025-04-28T20:22:23.908+0000] {logging_mixin.py:190} INFO - [2025-04-28T20:22:23.908+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:22:23.914+0000] {logging_mixin.py:190} INFO - [2025-04-28T20:22:23.913+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/lstm_refactored_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/lstm_refactored_dag.py", line 11, in <module>
    from src.utils.db_utils import setup_database
ModuleNotFoundError: No module named 'src'
[2025-04-28T20:22:23.914+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:22:23.925+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lstm_refactored_dag.py took 0.024 seconds
[2025-04-28T20:22:52.315+0000] {processor.py:186} INFO - Started process (PID=984) to work on /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:22:52.316+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lstm_refactored_dag.py for tasks to queue
[2025-04-28T20:22:52.318+0000] {logging_mixin.py:190} INFO - [2025-04-28T20:22:52.318+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:22:52.323+0000] {logging_mixin.py:190} INFO - [2025-04-28T20:22:52.323+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/lstm_refactored_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/lstm_refactored_dag.py", line 11, in <module>
    from src.utils.db_utils import setup_database
ModuleNotFoundError: No module named 'src'
[2025-04-28T20:22:52.324+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:22:52.335+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lstm_refactored_dag.py took 0.026 seconds
[2025-04-28T20:23:07.523+0000] {processor.py:186} INFO - Started process (PID=989) to work on /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:23:07.524+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lstm_refactored_dag.py for tasks to queue
[2025-04-28T20:23:07.525+0000] {logging_mixin.py:190} INFO - [2025-04-28T20:23:07.525+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:23:07.529+0000] {logging_mixin.py:190} INFO - [2025-04-28T20:23:07.528+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/lstm_refactored_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/lstm_refactored_dag.py", line 11, in <module>
    from src.utils.db_utils import setup_database
ModuleNotFoundError: No module named 'src'
[2025-04-28T20:23:07.529+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lstm_refactored_dag.py
[2025-04-28T20:23:07.540+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lstm_refactored_dag.py took 0.021 seconds
